### ISSUE TITLE
A question about face_detection

### ISSUE THREAD

**Issue by sunshiran171250501** [Saurav0074/Cartoon-Face-Detection-and-Recognition#2]
Hello, I appreciate your project about cartoon face detection. In the file `mtcnn_detect.py`, I noticed that the module `detect_face` is significant for the program and may contain the implementation of the paper mentioned in your `README.md`, but I couldn't find this module elsewhere in your project. Could you please let me get the `detect_face` module or the information of where to find it?
I sincerely look forward to your kind reply.

**Comment by srvCodes** [comment]
Hi there, as far as I remember, I used the detect_face module from an
external github implementation of MTCNN. Though I no longer have the access
to the correct github repo for it, I can suggest you use a similar but
easy-to-install python package that does the same work:
https://pypi.org/project/mtcnn/. Hope that was helpful!

Regards,
Saurav

**Comment by sunshiran171250501** [comment]
I see. Thank you so much!
